
Clojure for the Brave and True
learn the ultimate language and become a better programmer

Foreword
Introduction
Learning a New Programming Language: A Journey Through the Four Labyrinths
How This Book Is Organized
Part I: Environment Setup
The Code
The Journey Begins!
Chapter 1
Building, Running, and the REPL
First Things First: What Is Clojure?
Leiningen
Creating a New Clojure Project
Running the Clojure Project
Building the Clojure Project
Using the REPL
Clojure Editors
Summary
